version: '3.4'

services:
  webapi:
    image: ${DOCKER_REGISTRY-}webapi
    build:
      context: .
      dockerfile: WebApi/Dockerfile
  redis_image:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"
